### ISSUE TITLE
The software closes automatically when downloading files

### ISSUE THREAD

**Issue by onpxe** [RazielXT/mtTorrent#1]
[magnet:?xt=urn:btih:e3063b14a2714b0ee9f37a433cbd2f0df9098433&dn=%e5%bc%82%e7%95%8c.The.Coma.2019.BD720P.%e4%bf%84%e8%af%ad%e4%b8%ad%e5%ad%97.BTDX8&tr=udp%3a%2f%2fbt2.archive.org%3a6969%2fannounce&tr=http%3a%2f%2fmail2.zelenaya.net%3a80%2fannounce&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.nyaa.uk%3a6969%2fannounce&tr=http%3a%2f%2fbeautifull.top%3a6960%2fannounce&tr=https%3a%2f%2ftracker.nitrix.me%3a443%2fannounce&tr=udp%3a%2f%2fopen.nyap2p.com%3a6969%2fannounce&tr=https%3a%2f%2ftracker.sloppyta.co%3a443%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2fbt1.archive.org%3a6969%2fannounce&tr=http%3a%2f%2ftracker.yoshi210.com%3a6969%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&tr=udp%3a%2f%2fretracker.akado-ural.ru%3a80%2fannounce&tr=http%3a%2f%2ftracker.nyap2p.com%3a8080%2fannounce&tr=udp%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=udp%3a%2f%2fretracker.lanta-net.ru%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.pirateparty.gr%3a6969%2fannounce&tr=http%3a%2f%2ftracker.ygsub.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.zerobytes.xyz%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.sbsub.com%3a2710%2fannounce&tr=http%3a%2f%2fnovaopcj.icu%3a10325%2fannounce&tr=udp%3a%2f%2ftracker.gbitt.info%3a80%2fannounce&tr=udp%3a%2f%2fxxxtor.com%3a2710%2fannounce&tr=http%3a%2f%2ft.overflow.biz%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.uw0.xyz%3a6969%2fannounce&tr=http%3a%2f%2fbt2.archive.org%3a6969%2fannounce&tr=http%3a%2f%2fbt1.archive.org%3a6969%2fannounce&tr=http%3a%2f%2ftracker.gbitt.info%3a80%2fannounce&tr=http%3a%2f%2fretracker.sevstar.net%3a2710%2fannounce](url)

**Comment by RazielXT** [comment]
Thank you for report. Fixed in [commit](https://github.com/RazielXT/mtTorrent/commit/0cf5a07da0ae5e6f24ea397dc3341f6a54229c41)
