### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by onpxe** [RazielXT/mtTorrent#2]
![QQ截图20200514110333](https://user-images.githubusercontent.com/23578819/81887825-93966800-95d2-11ea-9837-65b66466a34c.png)

**Comment by onpxe** [comment]
[magnet:?xt=urn:btih:5afeb5b08587aaf9224267dcc80cefbaa4d5d527&dn=%e5%bc%82%e7%95%8c.The.Coma.2019.BD1080P.%e4%bf%84%e8%af%ad%e4%b8%ad%e5%ad%97.BTDX8&tr=udp%3a%2f%2fbt2.archive.org%3a6969%2fannounce&tr=http%3a%2f%2fmail2.zelenaya.net%3a80%2fannounce&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.nyaa.uk%3a6969%2fannounce&tr=http%3a%2f%2fbeautifull.top%3a6960%2fannounce&tr=https%3a%2f%2ftracker.nitrix.me%3a443%2fannounce&tr=udp%3a%2f%2fopen.nyap2p.com%3a6969%2fannounce&tr=https%3a%2f%2ftracker.sloppyta.co%3a443%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2fbt1.archive.org%3a6969%2fannounce&tr=http%3a%2f%2ftracker.yoshi210.com%3a6969%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&tr=udp%3a%2f%2fretracker.akado-ural.ru%3a80%2fannounce&tr=http%3a%2f%2ftracker.nyap2p.com%3a8080%2fannounce&tr=udp%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=udp%3a%2f%2fretracker.lanta-net.ru%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.pirateparty.gr%3a6969%2fannounce&tr=http%3a%2f%2ftracker.ygsub.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.zerobytes.xyz%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.sbsub.com%3a2710%2fannounce&tr=http%3a%2f%2fnovaopcj.icu%3a10325%2fannounce&tr=udp%3a%2f%2ftracker.gbitt.info%3a80%2fannounce&tr=udp%3a%2f%2fxxxtor.com%3a2710%2fannounce&tr=http%3a%2f%2ft.overflow.biz%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.uw0.xyz%3a6969%2fannounce&tr=http%3a%2f%2fbt2.archive.org%3a6969%2fannounce&tr=http%3a%2f%2fbt1.archive.org%3a6969%2fannounce&tr=http%3a%2f%2ftracker.gbitt.info%3a80%2fannounce&tr=http%3a%2f%2fretracker.sevstar.net%3a2710%2fannounce](url)

**Comment by RazielXT** [comment]
Yesterday I wasnt able to find any active peers for this magnet neither using BiglyBT. But today it was downloaded with both clients. 
![image](https://user-images.githubusercontent.com/378856/81906476-9be8a600-95c6-11ea-9d19-b5e325b23401.png)

Its possible this is because DHT table isnt filled enough yet. If problem persists you can try adding peer manually (left click on peers, Add peer, ip:port of any active peer from qbittorrent).

**Comment by RazielXT** [comment]
Forgot to mention, DHT is disabled by default, try enabling it for more peers
