### ISSUE TITLE
You can directly use ASIO with a stand-alone version

### ISSUE THREAD

**Issue by onpxe** [RazielXT/mtTorrent#4]
Change rapidjson to cjson

[asio.zip](https://github.com/RazielXT/mtTorrent/files/4626531/asio.zip)
[cJSON.zip](https://github.com/RazielXT/mtTorrent/files/4626535/cJSON.zip)

**Comment by onpxe** [comment]
Boost files are too large, too many

**Comment by RazielXT** [comment]
Hi, I moved to standalone ASIO already, boost shouldnt be used by project

**Comment by RazielXT** [comment]
> Change rapidjson to cjson

Any specific reason for change? I recommend using C++ API interface instead of json if possible

**Comment by RazielXT** [comment]
rapidjson usage removed
