### ISSUE TITLE
There is a problem with the project path setting, unable to compile

### ISSUE THREAD

**Issue by onpxe** [RazielXT/mtTorrent#5]
![QQ截图20200514150213](https://user-images.githubusercontent.com/23578819/81903158-e92f3c80-95f3-11ea-9eff-130eaf3fa0b3.png)

**Comment by RazielXT** [comment]
x64 is primary maintained platform, do you need x86 to be updated as well?

**Comment by onpxe** [comment]
Both x64 and x86 should support

**Comment by RazielXT** [comment]
x86 support added in [commit](https://github.com/RazielXT/mtTorrent/commit/1598df3d36f0e7a09a763b8a8c7532bb8ab8b18e)
