### ISSUE TITLE
Lots of error with mtTorrent.

### ISSUE THREAD

**Issue by meganthomas** [RazielXT/mtTorrent#7]
Getting a lot of error with mtTorrent. specifically. Attached screenshot for your reference. can you please help?
![error](https://user-images.githubusercontent.com/31311288/84703306-aacfc900-af75-11ea-97ef-52b90bd747ff.PNG)

**Comment by RazielXT** [comment]
Hi, looks like newer asio versions removed used call get_io_service(). [Fixed](https://github.com/RazielXT/mtTorrent/commit/c9ae3b651448040fe26fa860eba940b3f0b1d918)

**Comment by meganthomas** [comment]
Thank you so much ... It got sorted. RazielXT thanks a ton. I am working on a pet project and wanted to discuss with you, if you had time. Please let me know. I am reachable at rappercrazzy@gmail.com. 

Even if not, I understand. I thank you a ton for the help and this nice project. 

![Thanks](https://user-images.githubusercontent.com/31311288/84709227-795bfb00-af7f-11ea-8961-ddee79bba4f7.PNG)
